In [3]:
%run logistic_regr.py

In [25]:
%pylab

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


In [50]:
plt.plot(x1,x2)

In [27]:
plt.scatter(x_train[:,0],x_train[:,1],c=y_train, edgecolors='k', cmap=plt.cm.Paired )

In [8]:
plt.scatter(x_test[:,1],x_test[:,2],c=y_test, edgecolors='k', cmap=plt.cm.Paired )

IndexError: index 2 is out of bounds for axis 1 with size 2

In [53]:
%run svm_smo.py

0 0
1 0
2 0
3 0
4 0
0 0.0
1 1.0 0.0 -1.85 0.540540540541 1.0 0
0.540540540541
5 86
6 86
7 86
8 86
9 86
0 0.0
1 -0.145945945946 1.73513513514 -8.09 -0.232519293088 1.0 0
0.0
10 75
11 86
12 86
13 86
14 86
15 86
0 0.0
1 -0.113513513514 1.88108108108 -8.1 -0.246246246246 1.0 0
0.0
16 86
0 0.0
1 -0.2 1.99459459459 -11.72 -0.187252098515 1.0 0
0.0
17 86
18 86
19 86
20 86
21 75
22 75
23 86
24 86
25 86
26 75
27 86
28 75
29 75
30 86
31 86
32 75
33 86
34 86
35 86
36 75
37 75
38 75
39 75
40 75
41 86
42 86
43 86
44 86
45 86
46 86
47 86
48 75
49 75
50 75
51 86
52 86
53 86
54 86
55 86
56 86
57 86
58 75
59 86
60 75
61 86
62 75
63 75
64 86
65 86
66 86
67 86
68 86
69 86
70 75
71 75
72 86
73 75
74 75
0 0.0
-1 0.0216216216216 -2.08108108108 -9.97 -0.210902979208 1.0 0
0.0
75 86
0 0.0
1 -0.102702702703 2.17297297297 -10.61 -0.214484041063 1.0 0
0.0
76 75
77 86
78 75
79 86
80 86
81 86
82 86
83 86
84 75
85 75
86 75
0 0.0
-1 0.275675675676 -2.0 -10.61 -0.214484041063 1.0 0
0.0
87 86
88 86
89 86
90 86
91 75
9

In [47]:
w

array([ 0.5, -0.7])

In [51]:
alfas

array([ 0.51546392,  0.51546392,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

In [25]:
np.dot(x_train[1,:],x_train[2,:].T)

38.859999999999999

In [52]:
lin_svc = sklearn.svm.LinearSVC(C=C).fit(x_train, y_train)

NameError: name 'sklearn' is not defined

In [59]:
alphas = np.abs(svm.LinearSVC.dual_coef_)

AttributeError: type object 'LinearSVC' has no attribute 'dual_coef_'

In [55]:
lin_svc

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [62]:
a = svm.LinearSVC.get_params

In [63]:
a

<unbound method LinearSVC.get_params>

In [78]:
from SVM import SVM
model = SVM(max_iter=10000, kernel_type='linear', C=1.0, epsilon=0.001)

In [79]:
model.fit(x_train,y_train)

(array([[ 6.9,  3.2],
        [ 4.8,  3.4],
        [ 5. ,  3.4],
        [ 4.9,  2.5]]), 2)

In [70]:
alpha

NameError: name 'alpha' is not defined

In [68]:
model.fit.alpha

AttributeError: 'function' object has no attribute 'alpha'